# Generated by Django 5.1.6 on 2025-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True),
        ),
    ]
