# Generated by Django 5.1.6 on 2025-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field = models.CharField(max_length=150,blank=True,default="")
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True,default='',max_length=10),
        ),
    ]
